### ISSUE TITLE
Embed issue

### ISSUE THREAD

**Issue by jackakay** [N4T4NM/CSharpDiscordWebhook#11]
error thrown when sending an embed with hook.send(message);
System.Net.WebException: {embeds:["0"]}
thanks.

**Comment by MrNatanael** [comment]
What fields are you trying to send ?

**Comment by jackakay** [comment]
> What fields are you trying to send ?

Just a default embed (title and description) but it doesn't matter how many fields I add I get the same error.

**Comment by MrNatanael** [comment]
Can you submit your code to verify?
