### ISSUE TITLE
feat: Support for components

### ISSUE THREAD

**Issue by kgnfth** [N4T4NM/CSharpDiscordWebhook#16]
Can u pls support for https://discord.com/developers/docs/interactions/message-components#component-object

in js it looks like this

```js
  "components": [
    {
      "type": 1,
      "components": [
        {
          "style": 5,
          "label": `Open new issue`,
          "url": `https://github.com/N4T4NM/CSharpDiscordWebhook/issues/new`,
          "disabled": false,
          "type": 2
        },
      ]
    }
  ],
```

**Comment by N4T4NM** [comment]
Hello, I already tried to add support for components some time ago, but webhooks didn't support it.

But it seems that Discord added support for components on webhook messages, I will check this as soon as possible.

**Comment by N4T4NM** [comment]
After checking the documentation further, I found that Discord only supports components in messages sent by apps, because you need to be connected to the Discord gateway with a valid bot token to receive the component interactions events.

**Comment by kgnfth** [comment]
> After checking the documentation further, I found that Discord only supports components in messages sent by apps, because you need to be connected to the Discord gateway with a valid bot token to receive the component interactions events.

Aaahh okey
