### ISSUE TITLE
(Need Help) "Exception Thrown"

### ISSUE THREAD

**Issue by AntAptive** [N4T4NM/CSharpDiscordWebhook#20]
Hi, I'm having an issue where it just sends this in the output when I try to send a webhook.
`Exception thrown: 'CSharpDiscordWebhook.NET.Discord.DiscordException' in System.Private.CoreLib.dll`

Here's my code
```c#
public static async Task buildWebhook(string URL)
{
    System.Diagnostics.Debug.WriteLine("Sending Webhook to " + URL);
    DiscordWebhook hook = new DiscordWebhook();
    hook.Uri = new Uri(URL);

    DiscordMessage message = new DiscordMessage();
    message.Content = "Example message";
    message.Username = "Results Bot";

    DiscordEmbed embed = new DiscordEmbed();
    embed.Title = "Embed title";
    embed.Description = "Embed description";
    embed.Url = "Embed Url";
    embed.Timestamp = DateTime.Now;
    embed.Footer = new EmbedFooter() {Text = "Footer"};

    embed.Fields = new List<EmbedField>();
    embed.Fields.Add(new EmbedField() { Name = "Field Name", Value = "`Field Value`", InLine = true });
    embed.Fields.Add(new EmbedField() { Name = "Field Name 2", Value = "`Field Value 2`", InLine = true });

    message.Embeds = new List<DiscordEmbed>();
    message.Embeds.Add(embed);

    await hook.SendAsync(message);

    System.Diagnostics.Debug.WriteLine("Sent Webhook to "+URL);
}
```

I'm a beginner to C#, so please go easy on me haha. Any help is really appreciated!

**Comment by MrNatanael** [comment]
The "embed.Url" is setting a invalid URL, try removing it.

**Comment by AntAptive** [comment]
> The "embed.Url" is setting a invalid URL, try removing it.

Hi, setting it to both the intended URL and completely removing it does the same thing.

**Comment by MrNatanael** [comment]
I can't test the code right now. Put the method body inside a try catch, then use a Debug.Log to log the exception, and send the output so I can take a look at it.

**Comment by AntAptive** [comment]
Here's the output
```
{0} Exception Caught: CSharpDiscordWebhook.NET.Discord.DiscordException: error code: 1020
   at CSharpDiscordWebhook.NET.Discord.DiscordWebhook.SendAsync(DiscordMessage message, FileInfo[] files)
   at (redacted for post).Form1.buildWebhook(String URL) in C:\Users\Owner\source\repos\(redacted for post)\Form1.cs:line 57
```

**Comment by MrNatanael** [comment]
I searched for the error code, and all I could find was about cloudflare blocking the request. I can't test the code myself right now :/ maybe tomorrow...

**Comment by AntAptive** [comment]
Alrighty. Is there something I could do, like running the webhook through a proxy maybe?

**Comment by AntAptive** [comment]
Oh dear, it actually WAS because I was running it through a proxy, my apologies. Thank you for your help anyways!

**Comment by MrNatanael** [comment]
If you are using a VPN, try disabling it, or try using a proxy as you suggested. The only other problems I could think of is the lack of information (Like the User-Agent header) when sending a request.

**Comment by AntAptive** [comment]
Yeah, I was sending it to hooks.hyra.io instead of discord.com and that was why. Again, my deepest apologies. I forgot I put that in 😂
