### ISSUE TITLE
SendAsync Method doesn't exit, Nuget package outdated.

### ISSUE THREAD

**Issue by M0n7y5** [N4T4NM/CSharpDiscordWebhook#23]
Looks like nuget packages are outdated. Documentation doesn't reflect actual version of nuget package via visual studio package manager.

![obrazek](https://user-images.githubusercontent.com/17201053/211133623-d672ae53-1b5d-4aca-bb20-bf6d488f9a1a.png)

**Comment by MrNatanael** [comment]
NuGet package has been updated, version 2.7.1 has been pushed and should be avaiable soon.
