### ISSUE TITLE
Server error 404

### ISSUE THREAD

**Issue by decries** [N4T4NM/CSharpDiscordWebhook#3]
Any Help?
 `public static void SendLoginLog()
        {
            DiscordWebhook hook = new DiscordWebhook();
            hook.Url = "URL";
           
            DiscordMessage message = new DiscordMessage();
            message.Content = "New Log";
            message.TTS = false; //read message to everyone on the channel
            message.Username = "Predator new Login!";
            message.AvatarUrl = "https://cdn.discordapp.com/attachments/820460415062114344/820748997174100018/predatorlogo.jpg";

            //embeds
            DiscordEmbed embed = new DiscordEmbed();
            embed.Title = "New Login!";
            embed.Description = "Check User Logs in SafeGuard for more Info!.";
            embed.Url = "safeguardauth.us/#/developeradmin/manageuserlogs";
            embed.Timestamp = DateTime.Now;
            embed.Color = Color.Red; //alpha will be ignored, you can use any RGB color
            embed.Footer = new EmbedFooter() { Text = $"IP: {Tools.GetClientIP()}", IconUrl = "https://cdn.discordapp.com/attachments/820460415062114344/820748997174100018/predatorlogo.jpg" };
            embed.Provider = new EmbedProvider() { Name = "Google", Url = "https://google.com" };
            embed.Author = new EmbedAuthor() { Name = "Predator Security", Url = "Author Url", IconUrl = "https://cdn.discordapp.com/attachments/820460415062114344/820748997174100018/predatorlogo.jpg" };

            //fields
            embed.Fields = new[]{
            new EmbedField() {Name="Username: ", Value=$"{ResponseInformation.loginresponse.UserName}", InLine=true },
            new EmbedField() {Name="Plan: ", Value=$"{plan}", InLine=true }};

            //set embed
            message.Embeds = new[] { embed };
            hook.Send(message);
            Main frmMain = new Main();
            frmMain.ShowDialog();
        }`

**Comment by MrNatanael** [comment]
Can you send the full error message ?

**Comment by decries** [comment]
That's the full error, i tried sending a message with this code

`    
DiscordMessage message = new DiscordMessage();
        message.Content = "New Log"; 
hook.Send(message);`
`
And it worked, im going to assume the embed part is the issue

**Comment by MrNatanael** [comment]
please send the message shown in the exception window

**Comment by decries** [comment]
https://pays.host/uploads/643d8887-6535-4f38-a720-1bee9e94b54f/UPjnqUbn.png

Thats the Exception. Any help?

**Comment by MrNatanael** [comment]
The error is my fault, I will fix it soon.

**Comment by MrNatanael** [comment]
Hello, after some tests I came to the conclusion that the problem is in your code, always make sure that you are using valid urls.

Please change the lines below
```
embed.Url = "safeguardauth.us/#/developeradmin/manageuserlogs"
--> url needs to start with http:// or https://


embed.Author = new EmbedAuthor() { Name = "Predator Security", Url = "Author Url", IconUrl = "https://cdn.discordapp.com/attachments/820460415062114344/820748997174100018/predatorlogo.jpg" }
--> change the url in "Author Url"
```
