### ISSUE TITLE
Server error 400

### ISSUE THREAD

**Issue by ramoscarloss** [N4T4NM/CSharpDiscordWebhook#9]
![Screenshot_10](https://user-images.githubusercontent.com/85069173/130288611-92675d2f-970c-4df3-80c2-c82944c46813.png)

**Comment by MrNatanael** [comment]
Use a proxy and look at the server response

I'm updating the .Net Framework version to show the server response when errors happen

**Comment by MrNatanael** [comment]
Code updated, use it and check the server response
